export const bookings = [
    {
        id: 1,
        date: "10/10/2025",
        time: "09:00 AM",
        service: "Manicure",
        addOns: "Gel, Water",
        status: "Completed",
        type: "Team Member",
        name: "John Wick",
        location: "New York",
        avatar: "/images/logo.png",
        price: 45,
        icon: "🧑‍🔧",
    },
    {
        id: 2,
        date: "10/11/2025",
        time: "06:00 AM",
        service: "Manicure",
        addOns: "Gel, Water",
        status: "Upcoming",
        type: "Team Member",
        name: "John Wick",
        location: "New York",
        avatar: "/images/logo.png",
        price: 45,
        icon: "🧑‍🔧",
    },
    {
        id: 3,
        date: "10/12/2025",
        time: "09:00 AM",
        service: "Manicure",
        addOns: "Gel, Water",
        status: "Completed",
        type: "Customer",
        name: "John Wick",
        location: "New York",
        avatar: "/images/logo.png",
        price: 45,
        icon: "👤",
    },
    {
        id: 4,
        date: "10/13/2025",
        time: "09:00 AM",
        service: "Manicure",
        addOns: "Gel, Water",
        status: "Completed",
        type: "Customer",
        name: "John Wick",
        location: "New York",
        avatar: "/images/logo.png",
        price: 45,
        icon: "👤",
    },
    {
        id: 5,
        date: "10/13/2025",
        time: "09:00 AM",
        service: "Manicure",
        addOns: "Gel, Water",
        status: "Upcoming",
        type: "Customer",
        name: "John Wick",
        location: "New York",
        avatar: "/images/logo.png",
        price: 45,
        icon: "👤",
    },
    {
        id: 6,
        date: "10/13/2025",
        time: "09:00 AM",
        service: "Manicure",
        addOns: "Gel, Water",
        status: "Upcoming",
        type: "Customer",
        name: "John Wick",
        location: "New York",
        avatar: "/images/logo.png",
        price: 45,
        icon: "👤",
    },
];
